#ifndef DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED
#define DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED


#define DIRECT_LIGHTS_COUNT 1
#define POINT_LIGHTS_COUNT  1 //debug, 3


#endif // !DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED
