#ifndef DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED
#define DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED


#define DIRECT_LIGHTS_COUNT 1
#define POINT_LIGHTS_COUNT  3


//#define VIDEO_RECORDING_MODE

//#define USE_SMOOTH_REFRACTION_APPROX_BSDF

//#define CONVERT_SRGB_INPUT_TO_LINEAR
//#define CONVERT_LINEAR_OUTPUT_TO_SRGB

#endif // !DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED
